project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - ja/index.qmd

website:
  title: "Ken Morotomi"
  site-url: "https://kenmorotomi.github.io"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    anchor-sections: false
    smooth-scroll: true