project:
  type: website
  output-dir: docs

website:
  title: "Ken Morotomi"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
      - href: https://github.com/kenmorotomi
        text: GitHub
      - href: ja/index.qmd
        text: 日本語
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false